title: GBICi5-Scratch-1-Starter
hero_image: images/banner.png
description: GBICi5-Scratch-1-Starter description
version: 4
listed: false
copyedit: false
last_tested: "2019-08-13"
steps:
  - title: Starter
